### ISSUE TITLE
The error stream doesn't seem to work

### ISSUE THREAD

**Issue by prasanth-G24** [jwakely/pstreams#6]
I have written a python file containing some junk. I am doing this to find whether pstreams::pstderr is working properly. But only the pstreams::pstdout seems to work. These are the codes I have written.

### pstreams_test.cpp

```
#include <iostream>
#include "pstream.h"
using namespace redi;
main(){
    ipstream proc("python testfile.py", pstreams::pstdout | pstreams::pstderr);
    std::string line;
    while(getline(proc.out(), line))
    {
        std::cout<<line<<std::endl;
    }
    while(getline(proc.err(), line))
    {
        std::cout<<line<<std::endl;
    }
}
```

### testfile.py

```
you can
write_whatever
junk you want to
```

If you write a valid python code in testfile.py, I am getting the expected result.

Is there any change I need to make for making the pstderr work? Thanks in advance.

**Comment by jwakely** [comment]
After you read all the stdout the stream state gets the `eofbit` and `failbit` flags set, so `proc.eof() && proc.fail()` is true, and any further reads fail immediately. You need to reset the state before reading again:

```
    while(getline(proc.out(), line))
    {
        std::cout<<line<<std::endl;
    }
    if (proc.eof())
        proc.clear();
    while(getline(proc.err(), line))
    {
        std::cout<<line<<std::endl;
    }
```

(Also, your `main` is missing a return type, which is not valid C++).

**Comment by prasanth-G24** [comment]
> After you read all the stdout the stream state gets the `eofbit` and `failbit` flags set, so `proc.eof() && proc.fail()` is true, and any further reads fail immediately. You need to reset the state before reading again:
> 
> ```
>     while(getline(proc.out(), line))
>     {
>         std::cout<<line<<std::endl;
>     }
>     if (proc.eof())
>         proc.clear();
>     while(getline(proc.err(), line))
>     {
>         std::cout<<line<<std::endl;
>     }
> ```
> 
> (Also, your `main` is missing a return type, which is not valid C++).

In Linux you don't give a return type, if your main has a void return type.

**Comment by jwakely** [comment]
No, that's 100% wrong. This has nothing to do  with Linux. Allowing you to omit the return type is a GCC extension, which is independent of your OS, but is not valid C++. And `main` has return type `int` even if you omit that return type and rely on the non-standard extension. Otherwise this wouldn't compile:

`main() { return 0; }`

My point is that you're relying on non-standard extension, which gives a warning by default in current versions of GCC:

```
v.cc:4:6: warning: ISO C++ forbids declaration of ‘main’ with no type [-Wreturn-type]
    4 | main()
      |      ^
```

And I don't usually bother responding to people who don't fix warnings.

**Comment by prasanth-G24** [comment]
> No, that's 100% wrong. This has nothing to do with Linux. Allowing you to omit the return type is a GCC extension, which is independent of your OS, but is not valid C++. And `main` has return type `int` even if you omit that return type and rely on the non-standard extension. Otherwise this wouldn't compile:
> 
> `main() { return 0; }`
> 
> My point is that you're relying on non-standard extension, which gives a warning by default in current versions of GCC:
> 
> ```
> v.cc:4:6: warning: ISO C++ forbids declaration of ‘main’ with no type [-Wreturn-type]
>     4 | main()
>       |      ^
> ```
> 
> And I don't usually bother responding to people who don't fix warnings.

I'm not that much of a c++ expert Jonathan, but I'm pretty sure I didn't get a warning during compilation. Otherwise I would've changed it. This piece of code, with some modifications, is going to be pushed to production and pushing with warnings is not allowed in my org. 

Thanks very much for helping me out.
