### ISSUE TITLE
clang-tidy complains of virtual function dispatch bypass

### ISSUE THREAD

**Issue by tangentsoft** [jwakely/pstreams#7]
If you run `clang-tidy test_pstreams.cc` you get this complaint:

```
.../pstream.h:1621:7: note: Call to virtual method 'basic_pstreambuf::sync' during destruction bypasses virtual dispatch
```

I'm not sure what it's babbling about since `sync()` isn't virtual. Is `clang-tidy` stoned, or has it actually got a point here?

**Comment by jwakely** [comment]
`sync` is virtual, it overrides a function in the base class. I'll take a look.

**Comment by jwakely** [comment]
Bypassing virtual dispatch is actually exactly what we want here, so the code is correct, but subtle. Clang-tidy can't tell that it's intentional rather than a mistake. I'll change it to call `basic_streambuf::sync();` to make the intended behaviour explicit.

**Comment by jwakely** [comment]
That should fix it. Thanks for reporting the issue!

**Comment by tangentsoft** [comment]
Confirmed in the real-world case where I originally found it. Thanks for the fix!
